# SPDX-FileCopyrightText: 2021 Michel Oosterhof <michel@oosterhof.net>
#
# SPDX-License-Identifier: BSD-3-Clause

---
volumes:
  cowrie-etc:
  cowrie-var:

services:
  cowrie:
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - cowrie-etc:/cowrie/cowrie-git/etc
      - ../var:/cowrie/cowrie-git/var
      - ../etc/cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg:ro
      - ../etc/userdb.txt:/cowrie/cowrie-git/etc/userdb.txt:ro
      - ../etc/motd:/cowrie/cowrie-git/honeyfs/etc/motd:ro

  dashboard:
    restart: always
    build:
      context: ..
      dockerfile: dashboard/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ../var:/cowrie/cowrie-git/var
    depends_on:
      - cowrie
